- name: Setup Jenkins Server with all necessary tools
  hosts: jenkins-server
  become: yes
  tasks:
    - name: Update apt cache and install initial dependencies
      apt:
        name: 
          - openjdk-17-jre
          - git
          - software-properties-common # Needed for adding repositories
        state: present
        update_cache: yes

    # --- Install Jenkins ---
    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes # Update cache again after adding new repo

    - name: Start and enable the Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    # --- Install Terraform ---
    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present

    - name: Install Terraform
      apt:
        name: terraform
        state: present
        update_cache: yes # Update cache again after adding new repo

    # --- Install Ansible ---
    - name: Add Ansible repository
      apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes # Update cache again after adding new repo