name: Deploy Stripe App to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        id: tf_apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Setup Ansible and Deploy
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible-key.pem
          chmod 400 ansible-key.pem

          echo "stripe_publishable_key: ${{ secrets.STRIPE_PK }}" > secrets.yml
          echo "stripe_secret_key: ${{ secrets.STRIPE_SK }}" >> secrets.yml

          APP_SERVER_IP=$(terraform output -raw public_ip)

          echo "[webserver]" > inventory_github
          echo "$APP_SERVER_IP ansible_user=ubuntu ansible_ssh_private_key_file=./ansible-key.pem" >> inventory_github

          ansible-playbook -i inventory_github playbook.yml