name: Deploy Stripe App to AWS (Simple)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy Application using SSH
        run: |
          APP_SERVER_IP=$(terraform output -raw public_ip)
          echo "Deploying to server: $APP_SERVER_IP"

          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$APP_SERVER_IP 'bash -s' <<'EOF'
            # These commands are now running on the remote server
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm git
            git clone https://github.com/verma-kunal/AWS-Session.git
            cd AWS-Session
            echo "PUBLISHABLE_KEY=${{ secrets.STRIPE_PK }}" > .env
            echo "SECRET_KEY=${{ secrets.STRIPE_SK }}" >> .env
            npm install
            sudo npm install pm2 -g
            pm2 startOrReload server.js --name "stripe-app"
          EOF