name: Deploy Stripe App to AWS (Final)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy Application via SSH
        run: |
          # Extract the IP address reliably
          APP_SERVER_IP=$(terraform output -raw public_ip | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
          echo "Server IP is $APP_SERVER_IP"

          # Create the SSH key file
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

          # Create a deployment script file
          cat > deploy_script.sh <<EOF
          #!/bin/bash
          set -e

          # Update and install dependencies
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm git

          # Clone the repository
          git clone https://github.com/verma-kunal/AWS-Session.git
          cd AWS-Session

          # Create .env file with secrets
          echo "PUBLISHABLE_KEY=${{ secrets.STRIPE_PK }}" > .env
          echo "SECRET_KEY=${{ secrets.STRIPE_SK }}" >> .env

          # Install app dependencies and PM2
          npm install
          sudo npm install pm2 -g

          # Start the app with PM2
          pm2 startOrReload server.js --name "stripe-app"
          EOF

          # Copy the script to the new server
          scp -o StrictHostKeyChecking=no -i private_key.pem ./deploy_script.sh ubuntu@$APP_SERVER_IP:/home/ubuntu/

          # Execute the script on the new server
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$APP_SERVER_IP "chmod +x /home/ubuntu/deploy_script.sh && /home/ubuntu/deploy_script.sh"